version: '3.5'
services:
  solenya_express_api:
    container_name: solenya_express_api
    build: .
    image: solenya_express_api
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - POSTGRES_HOST=solenya_database
    depends_on:
      - solenya_database
    env_file:
      - .env
    ports:
      - 7770:7770
  solenya_database:
    container_name: solenya_postgres_db
    image: postgres:9.6
    volumes:
      - solenya_database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
  solenya_database: