version: '3.5'

services:
  api:
    image: registry.chas.school/solenya-api-dev:latest
    working_dir: /app
    command: node dist/server.js
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
    env_file:
      - .env.dev
    networks:
      - traefik
      - backend
    deploy:
      labels:
        traefik.port: '7770'
        traefik.backend: 'solenya_dev'
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:solenya-api-dev.chas.school'
  database:
    image: 'postgres:9.6'
    volumes:
      - 'database:/var/lib/postgresql/data'
    env_file:
      - .env.dev
    networks:
      - backend
    deploy:
      labels:
        traefik.enable: 'false'

volumes:
  database:

networks:
  traefik:
    external: true
  backend:
    external: false